config/routes.rb
Rails.application.routes.draw do
  get 'external_pages/show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'question_tops/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'questions#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :questions
    post 'questions/create', to: 'questions#create', as: :create_question
  end

  resources :questions do
    collection do
      get 'nutrition_display'
      post 'nutrition_answer'
      get 'nutrition_explanation'
      get 'compound_display'
      post 'compound_answer'
      get 'compound_explanation'
    end
  end

  resources :results do
    collection do
      get 'wrong_display'
      post 'wrong_answer'
      get 'wrong_explanation'
    end
  end

  resources :external_pages, only: %i[index]
  resources :terms, only: %i[index]

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :results, dependent: :destroy
  has_many :choices, dependent: :destroy

  validates  :content, presence: true
  validates  :reason, presence: true

  scope :incorrect, -> { joins(:results).where(results: { result: false }) }

  # マイステータス、円グラフのデータ抽出
  def self.nutrition_data(user)
    nutrition_count = where(type: 'Nutrition').count
    nutrition_true_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: true }).count
    nutrition_false_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: false }).count
    not_answer_count = nutrition_count - (nutrition_true_count + nutrition_false_count)

    { '正解' => nutrition_true_count, '不正解' => nutrition_false_count, '未回答' => not_answer_count }
  end

  def self.compound_data(user)
    compound_count = where(type: 'Compound').count
    compound_true_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: true }).count
    compound_false_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: false }).count
    not_answer_count = compound_count - (compound_true_count + compound_false_count)

    { '正解' => compound_true_count, '不正解' => compound_false_count, '未回答' => not_answer_count }
  end

  # 残りの問題数の取得
  def self.nutrition_rest_count(user)
    rest_count = Result.nutrition_count(user)
    questions_count = Question.where(type: 'nutrition').count
    questions_count - rest_count
  end

  def self.compound_rest_count(user)
    rest_count = Result.compound_count(user)
    questions_count = Question.where(type: 'compound').count
    questions_count - rest_count
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  # require 'active_support/core_ext/hash/keys'
  require 'json'

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = QuestionCreateForm.new
  end

  def edit
    edit_question = Question.find(params[:id])
    @question_form = QuestionCreateForm.new(question_id: edit_question.id,
                                            content: edit_question.content,
                                            reason: edit_question.reason,
                                            hint: edit_question.hint,
                                            type: edit_question.type,
                                            choices: {
            choice1: edit_question.choices.first.choice,
            correct1: edit_question.choices.first.correct,
            choice2: edit_question.choices.second.choice,
            correct2: edit_question.choices.second.correct,
            choice3: edit_question.choices.third.choice,
            correct3: edit_question.choices.third.correct,
            choice4: edit_question.choices.fourth.choice,
            correct4: edit_question.choices.fourth.correct
        })
    # hash = eval(@question_form.choices)
    hash = JSON.parse(@question_form.choices)
    @parsed_hash = JSON.parse(hash.to_json, symbolize_name: true)
  end

  def create
    @question = QuestionCreateForm.new(question_params)

    if @question.save_with_choices(
      choice_choice1: params.dig(:question_create_form, :choices, :choice1),
      choice_correct1: params.dig(:question_create_form, :choices, :correct1),
      choice_choice2: params.dig(:question_create_form, :choices, :choice2),
      choice_correct2: params.dig(:question_create_form, :choices, :correct2),
      choice_choice3: params.dig(:question_create_form, :choices, :choice3),
      choice_correct3: params.dig(:question_create_form, :choices, :correct3),
      choice_choice4: params.dig(:question_create_form, :choices, :choice4),
      choice_correct4: params.dig(:question_create_form, :choices, :correct4)
    )
      redirect_to admin_question_path(@question.question_id), success: '問題を作成しました'
    else
      flash.now[:danger] = '問題の作成に失敗しました'
      render :new
    end
  end

  def update
    @question = QuestionCreateForm.new(question_params)

    if @question.update_with_choices(
      question_id: params[:id],
      content: params.dig(:question_create_form, :content),
      reason: params.dig(:question_create_form, :reason),
      hint: params.dig(:question_create_form, :hint),
      type: params.dig(:question_create_form, :type),
      choice_choice1: params.dig(:question_create_form, :choices, :choice1),
      choice_correct1: params.dig(:question_create_form, :choices, :correct1),
      choice_choice2: params.dig(:question_create_form, :choices, :choice2),
      choice_correct2: params.dig(:question_create_form, :choices, :correct2),
      choice_choice3: params.dig(:question_create_form, :choices, :choice3),
      choice_correct3: params.dig(:question_create_form, :choices, :correct3),
      choice_choice4: params.dig(:question_create_form, :choices, :choice4),
      choice_correct4: params.dig(:question_create_form, :choices, :correct4)
    )
      redirect_to admin_question_path(@question.question_id), success: '問題を更新しました'
    else
      flash.now[:danger] = '問題の変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
    redirect_to admin_questions_path, notice: '問題を削除しました'
  end

  private

  def question_params
    params.require(:question_create_form).permit(:content, :reason, :hint, :type, choices: [:choice1, :correct1, :choice2, :correct2, :choice3, :correct3, :choice4, :correct4])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_layout, only: [:nutrition_display, :nutrition_explanation, :compound_display, :compound_explanation]

  # nutritionクイズ画面の表示アクション
  def nutrition_display
    user = current_user
    null_results = Question.where.not(id: Result.where(user_id: user.id).select(:question_id))

    if null_results.empty?
      @question = nil
      flash[:notice] = '問題は全て解答済みです'
      redirect_to question_tops_index_path
      return
    end

    @question = null_results.find_by(type: 'nutrition')

    if @question.blank?
      flash[:notice] = '問題は全て解答済みです'
      redirect_to question_tops_index_path
      return
    end

    @choices = @question.choices
    @nutrition_count = Question.nutrition_rest_count(user)
  end

  # クイズの回答処理アクション
  def nutrition_answer
    @question = Question.find(params[:id])
    @choices = @question.choices

    if params.key?(:selected_choice_id)
      # ユーザーが選択した解答のID
      selected_choice_id = params[:selected_choice_id].to_i
    else
      flash.now[:notice] = '選択してください'
      render :nutrition_display
      return
    end

    # 問題の正解のIDを取得
    # correct_choice_id = @question.choices.where(correct: true).select(:id)
    correct_choice_id = @question.choices.where(correct: true).pluck(:id)

    if correct_choice_id.include?(selected_choice_id)
      current_user.results.create(question_id: @question.id, result: 1)
    else
      current_user.results.create(question_id: @question.id, result: 0)
    end
    redirect_to nutrition_explanation_questions_path(id: @question.id)

    # 　ランク処理
    if current_user.rank.present?
      update_rank(current_user)
    else
      user_rank = Rank.calculate_rank(current_user)
      current_user.update(rank: user_rank)
    end
  end

  # 解説表示アクション
  def nutrition_explanation
    @question = Question.find(params[:id])
    result_instance = current_user.results.find_by(question_id: @question.id)
    @result_value = result_instance.result
  end

  # compoundクイズ画面の表示アクション
  def compound_display
    user = current_user
    null_results = Question.where.not(id: Result.where(user_id: user.id).select(:question_id))

    if null_results.empty?
      flash[:notice] = '問題は全て解答済みです'
      redirect_to question_tops_index_path
      return
    end

    @question = null_results.find_by(type: 'compound')

    if @question.blank?
      flash[:notice] = '問題は全て解答済みです'
      redirect_to question_tops_index_path
      return
    end

    @choices = @question.choices
    @compound_count = Question.compound_rest_count(user)
  end

  # クイズの回答処理アクション
  def compound_answer
    @question = Question.find(params[:id])
    @choices = @question.choices

    # ユーザーが選択した解答のID
    selected_choice_ids = params[:selected_choice_ids]

    if selected_choice_ids.present?
      selected_choice_ids = selected_choice_ids.flatten.map(&:to_i)
    else
      flash.now[:notice] = '選択してください'
      render :compound_display
      return
    end

    # 問題の正解のIDを取得
    # correct_choice_ids = @question.choices.where(correct: true).select(:id)
    correct_choice_ids = @question.choices.where(correct: true).pluck(:id)

    if correct_choice_ids.sort == (selected_choice_ids&.sort || [])
      current_user.results.create(question_id: @question.id, result: 1)
    else
      current_user.results.create(question_id: @question.id, result: 0)
    end
    redirect_to compound_explanation_questions_path(id: @question.id)

    # 　ランク処理
    if current_user.rank.present?
      update_rank(current_user)
    else
      user_rank = Rank.calculate_rank(current_user)
      current_user.update(rank: user_rank)
    end
  end

  # 解説表示アクション
  def compound_explanation
    @question = Question.find(params[:id])
    result_instance = current_user.results.find_by(question_id: @question.id)
    @result_value = result_instance.result
  end

  private

  def set_layout
    case action_name
    when 'nutrition_display', 'nutrition_explanation'
      self.class.layout 'nutrition'
    when 'compound_display', 'compound_explanation'
      self.class.layout 'compound'
    end
  end

  def update_rank(user)
    # ユーザーの現在のランクを取得
    current_rank = user.rank

    new_rank = Rank.calculate_rank(user)

    # 現在のランクと同じであれば、何もせず終了
    return if current_rank == new_rank

    # 異なる場合ユーザーのランクを更新する処理
    user.update(rank: new_rank)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/compound_display.html.erb
<div class="flex items-center justify-center">
    <div class="container  dark:text-black">
        <div class="pt-10 text-question-title w-1/3 rounded-sm mx-auto">
            <h1 class="text-1xl md:text-3xl py-5 bg-question-titlebg text-center opacity-80 rounded-full"><%= t '.title' %></h1>
        </div>
        <div class="pt-5 w-1/3 rounded-sm mx-auto text-top-font font-medium">
            <h1 class="text-sm md:text-2xl py-5 text-center">残り<%= @compound_count %>問</h1>
        </div>

        <div class="mt-10 w-3/5 opacity-80 mx-auto text-center">
            <div class="collapse bg-base-200">
                <input type="checkbox" /> 
                <div class="collapse-title text-xl font-medium">
                    ヒントを見る
                </div>
                <div class="collapse-content"> 
                    <%= @question.hint %>
                </div>
            </div>
        </div>

        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-80 mx-auto">
            <%= form_with(url: "/questions/compound_answer", method: "post", local: true) do |form| %>
                <%= form.hidden_field :id, value: @question.id %>
                <div class="pb-5 font-light">
                    <%= @question.content %>
                </div>
                <% @choices.each do |choice| %>
                    <label>
                        <%= form.check_box "selected_choice_ids[]", { multiple: true }, choice.id, nil %>
                        <%= choice.choice %>
                    </label><br>
                <% end %>
                <div class="mt-5 text-center">
                    <%= submit_tag '回答', class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/compound_explanation.html.erb
<div class="flex items-center justify-center">
    <div class="container">

        <%= render partial: 'shared/errata' %>

        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-70 mx-auto">
            <div>
                <%= @question.reason %>
            </div>
            <div class="flex justify-center mt-5">
                <%= button_to '問題選択画面へ', question_tops_index_path, class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button', method: :get %>
                <%= button_to '次の問題へ', compound_display_questions_path, class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button ml-3', method: :get %>
            </div>
        </div>
    </div>
</div>

app/views/questions/nutrition_display.html.erb
<div class="flex items-center justify-center">
    <div class="container dark:text-blackdark:text-black">
        <div class="pt-10 text-question-title w-1/3 rounded-sm mx-auto">
            <h1 class="text-1xl md:text-3xl py-5 bg-question-titlebg text-center opacity-80 rounded-full"><%= t '.title' %></h1>
        </div>
        <div class="pt-5 w-1/3 rounded-sm mx-auto font-medium text-top-font">
            <h1 class="text-sm md:text-2xl py-5 text-center">残り<%= @nutrition_count %>問</h1>
        </div>
        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-80 mx-auto">
            <%= form_with(url: "/questions/nutrition_answer", method: "post", local: true) do |form| %>
                <%= form.hidden_field :id, value: @question.id %>
                <div class="pb-5 font-light">
                    <%= @question.content %>
                </div>
                <% @choices.each do |choice| %>
                    <label>
                        <%= form.radio_button :selected_choice_id, choice.id %>
                        <%= choice.choice %>
                    </label><br>
                <% end %>
                <div class="mt-5 text-center">
                    <%= submit_tag '回答', class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/nutrition_explanation.html.erb
<div class="flex items-center justify-center">
    <div class="container">
        
        <%= render partial: 'shared/errata' %>

        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-70 mx-auto">
            <div>
                <%= @question.reason %>
            </div>
            <div class="flex justify-center mt-5">
                <%= button_to '問題選択画面へ', question_tops_index_path, class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button', method: :get %>
                <%= button_to '次の問題へ', nutrition_display_questions_path, class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button ml-3', method: :get %>
            </div>
        </div>
    </div>
</div>

app/views/questions/question_display.html.erb
<div>
    <div class="text-3xl pt-10 ml-10">
        <h1 class="text-3xl pt-10 ml-10"><%= t '.title' %></h1>
    </div>
    <div class="w-20 h-20 rounded-x1">
        <%= form_with(url: "/questions/question_answer", method: "post", local: true) do |form| %>
            <%= form.hidden_field :id, value: @question.id %>
            <div>
                <%= @question.content %>
            </div>
            <% @choices.each do |choice| %>
                <label>
                    <%= form.radio_button :selected_choice_id, choice.id %>
                    <%= choice.choice %>
                </label><br>
            <% end %>
            <div>
                <%= submit_tag '回答', class: 'btn btn-danger mx-1' %>
            </div>
        <% end %>
    </div>

</div>