config/routes.rb
Rails.application.routes.draw do
  get 'external_pages/show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'question_tops/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'questions#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :questions
    post 'questions/create', to: 'questions#create', as: :create_question
  end

  resources :questions do
    collection do
      get 'nutrition_display'
      post 'nutrition_answer'
      get 'nutrition_explanation'
      get 'compound_display'
      post 'compound_answer'
      get 'compound_explanation'
    end
  end

  resources :results do
    collection do
      get 'wrong_display'
      post 'wrong_answer'
      get 'wrong_explanation'
    end
  end

  resources :external_pages, only: %i[index]
  resources :terms, only: %i[index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question

  validates  :choice, presence: true
  validates :correct, inclusion: [true, false]
end

app/models/compound.rb
class Compound < Question
end

app/models/nutrition.rb
class Nutrition < Question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :results, dependent: :destroy
  has_many :choices, dependent: :destroy

  validates  :content, presence: true
  validates  :reason, presence: true

  scope :incorrect, -> { joins(:results).where(results: { result: false }) }

  # マイステータス、円グラフのデータ抽出
  def self.nutrition_data(user)
    nutrition_count = where(type: 'Nutrition').count
    nutrition_true_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: true }).count
    nutrition_false_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: false }).count
    not_answer_count = nutrition_count - (nutrition_true_count + nutrition_false_count)

    { '正解' => nutrition_true_count, '不正解' => nutrition_false_count, '未回答' => not_answer_count }
  end

  def self.compound_data(user)
    compound_count = where(type: 'Compound').count
    compound_true_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: true }).count
    compound_false_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: false }).count
    not_answer_count = compound_count - (compound_true_count + compound_false_count)

    { '正解' => compound_true_count, '不正解' => compound_false_count, '未回答' => not_answer_count }
  end

  # 残りの問題数の取得
  def self.nutrition_rest_count(user)
    rest_count = Result.nutrition_count(user)
    questions_count = Question.where(type: 'nutrition').count
    questions_count - rest_count
  end

  def self.compound_rest_count(user)
    rest_count = Result.compound_count(user)
    questions_count = Question.where(type: 'compound').count
    questions_count - rest_count
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  has_many :users

  validates :rank_name, presence: true
  validates :response, presence: true

  def self.calculate_rank(user)
    new_rank = nil
    # ユーザーの正解の回答数を取得
    result_count = Result.result_count(user)

    # 　ランク一覧をデータベースから取得
    ranks = Rank.order(response: :asc)
    ranks.each do |rank|
      if rank.response >= result_count
        new_rank = rank
        break # ユーザーのランクが見つかったらループ終了
      end
    end
    new_rank
  end
end

app/models/result.rb
class Result < ApplicationRecord
  enum result: { failure: 0, success: 1 }

  belongs_to :user
  belongs_to :question

  validates  :result, presence: true
  validates :question_id, uniqueness: { scope: :user_id }

  # 与えられたユーザーのresultカラムがtrueのレコード数を取得
  def self.result_count(user)
    where(user_id: user.id, result: true).count
  end

  # 回答した問題数の取得
  def self.nutrition_count(user)
    Result.joins(:question).where(questions: { type: 'nutrition' }).where(user_id: user.id).count
  end

  def self.compound_count(user)
    Result.joins(:question).where(questions: { type: 'compound' }).where(user_id: user.id).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum role: { general: 0, admin: 1 }

  has_many :results, dependent: :destroy
  belongs_to :rank, optional: true

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { minimum: 2 }

  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def show
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  layout 'top'
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
        site: 'FoodFit',
        title: '栄養に関する学習クイズサイト',
        reverse: true,
        charset: 'utf-8',
        description: 'FoodFitで日常で役立つ栄養学習が手軽に行えます',
        keywords: '栄養,クイズ,食事',
        canonical: request.original_url,
        separator: '|',
        og: {
            site_name: :site,
            title: :title,
            description: :description,
            type: 'website',
            url: request.original_url,
            image: image_url('ogp.jpg'),
            local: 'ja_JP'
        },

        twitter: {
            card: 'summary_large_image',
            image: image_url('ogp.jpg')
        }
    }
  end
end

app/helpers/conpunds_helper.rb
module ConpundsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4/css/bootstrap.min.css">
  </head>

  <body class="bg-admin-bg">
  <%= render 'shared/flash_message' %>
  
    <%= yield %>
  </body>
</html>

app/views/admin/shard/_question.html.erb
<ul class="inline-block">
    <li class="linline-block">
        <%= question.id %>  
    </li>
    <li class="inline-block">
        <%= question.content %> 
    </li>
</ul>

app/views/shared/_before_login_header.html.erb
<header>
    <div class="w-full flex mx-auto mt-26 text-center bg-header-color opacity-80 text-white h-16 py-5 md:h-28 md:py-10">
        <div class="mx-3 md:mx-6 my-link">
            <a href="<%= root_path %>" class="flex items-center text-white">
                <i class="fas fa-utensils text-2xl md:text-4xl mb-1"></i>
                <span class="ml-3 text-xl md:text-2xl font-bold font-HiraMinProN-W6">FoodFit</span>
            </a>
        </div>
        <div class="mx-3 md:mx-6 my-link">
            <%= link_to "新規登録", new_user_path %>
        </div>
        <div class="mx-3 md:mx-6 my-link">
            <%= link_to "ログイン", login_path %>
        </div>
    </div>
</header>

app/views/shared/_errata.html.erb
<div class="pt-10 text-question-title rounded-sm mx-auto w-1/3">
    <div class="<%= @result_value == 'success' ? 'bg-success-color' : 'bg-failure-color' %> text-1xl md:text-3xl py-5 text-center opacity-70 rounded-full">
        <% if @result_value == "success" %>
            正解！
        <% else @result_value == "failure" %>
            不正解
        <% end %>
    </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="p-4 mb-4 border rounded-lg <%= message_type == 'notice' ? 'bg-flash-color' : 'bg-red-200 border-red-400' %>">
        <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-bottom">
  <div class="w-full text-center bg-footer-color opacity-50 h-16 py-5 md:h-28 md:py-10">
    <div class="flex mx-auto text-white ">
      <div class="flex-1 text-xs md:text-lg">
      <a href="https://www.kiyac.app/privacypolicy/EOB9WgvtY2Ft45WpCqMJ">
        <button class="button">プライバシー・ポリシー</button>
      </div>
      <div class="flex-1 text-xs md:text-lg">
        <a href="<%= terms_path %>">
          <button class="button">利用規約</button>
        </a>
      </div>
      <div class="flex-1 text-xs md:text-lg">
        <a href="https://forms.gle/KfTMmxZQ9oiDkj3B6">
        <button class="button">お問い合わせ</button>
        </a>
      </div>
    </div>
    <div class="copyright text-center mt-2 text-xs md:text-lg">
      <p class="text-black"> © 2023.FoodFit</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="w-full flex mx-auto mt-26 text-center bg-header-color opacity-80 text-white h-16 py-5 md:h-28 md:py-10">
        <div class="mx-3 md:mx-6 my-link">
            <a href="<%= root_path %>" class="flex items-center text-white">
                <i class="fas fa-utensils text-2xl md:text-4xl mb-1"></i>
                <span class="ml-3 text-xl md:text-2xl font-bold font-HiraMinProN-W6">FoodFit</span>
            </a>
        </div>

        <div class="ml-auto mr-10 flex">
            <div class="ml-auto mx-3 md:mx-6 my-link md:text-xl text-mase">
                <%= link_to "問題を解く", question_tops_index_path %>
            </div>
            <nav>
                <button id="button" type="button" class="fixed z-10">
                    <i id="bars" class="fa-solid fa-bars fa-xl" style="color: #1f512b;"></i>
                    <i id="xmark" class="fa-solid fa-xmark fa-xl hidden" style="color: #582d09;"></i>
                </button>
                <ul id="menu" class="z-0 fixed top-0 left-0 w-full text-center bg-footer-color text-white font-bold translate-x-full transition ease-linear">
                    <div class="my-link">
                        <li class="p-3"><%= link_to "マイステータス", profile_path, data: {"turbolinks" => false} %></li>
                    </div>
                    <div class="my-link">
                        <li class="p-3"><%= link_to "設定", edit_profile_path %></li>
                    </div>
                    <li class="p-3"><%= button_to "ログアウト", logout_path, method: :delete, class: 'button' %></li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<main>
    <script>
        button.addEventListener('click', event => {
            bars.classList.toggle('hidden')
            xmark.classList.toggle('hidden')
            menu.classList.toggle('translate-x-full')
        });
    </script>
</main>