config/routes.rb
Rails.application.routes.draw do
  get 'external_pages/show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'question_tops/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'questions#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :questions
    post 'questions/create', to: 'questions#create', as: :create_question
  end

  resources :questions do
    collection do
      get 'nutrition_display'
      post 'nutrition_answer'
      get 'nutrition_explanation'
      get 'compound_display'
      post 'compound_answer'
      get 'compound_explanation'
    end
  end

  resources :results do
    collection do
      get 'wrong_display'
      post 'wrong_answer'
      get 'wrong_explanation'
    end
  end

  resources :external_pages, only: %i[index]
  resources :terms, only: %i[index]

end

app/models/result.rb
class Result < ApplicationRecord
  enum result: { failure: 0, success: 1 }

  belongs_to :user
  belongs_to :question

  validates  :result, presence: true
  validates :question_id, uniqueness: { scope: :user_id }

  # 与えられたユーザーのresultカラムがtrueのレコード数を取得
  def self.result_count(user)
    where(user_id: user.id, result: true).count
  end

  # 回答した問題数の取得
  def self.nutrition_count(user)
    Result.joins(:question).where(questions: { type: 'nutrition' }).where(user_id: user.id).count
  end

  def self.compound_count(user)
    Result.joins(:question).where(questions: { type: 'compound' }).where(user_id: user.id).count
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_layout, only: [:wrong_display, :wrong_explanation]

  # クイズ表示
  def wrong_display
    current_user
    wrong_questions = Question.incorrect.pluck(:id)
    if wrong_questions.present?
      wrong_random = wrong_questions.sample
      @question = Question.find_by(id: wrong_random)
      @choices = @question.choices
    else
      flash[:notice] = '問題は全て解答済みです'
      redirect_to question_tops_index_path
    end
  end

  # クイズ回答
  def wrong_answer
    @question = Question.find(params[:id])
    @choices = @question.choices

    if @question.type == 'Compound'
      type_compound
    else
      type_other
    end
  end

  # 回答表示
  def wrong_explanation
    @question = Question.find(params[:id])
    result_instance = current_user.results.find_by(question_id: @question.id)
    @result_value = result_instance.result
  end

  private

  def set_layout
    self.class.layout 'wrong'
  end

  def type_compound
    # ユーザーが選択した解答のID
    selected_choice_ids = params[:selected_choice_ids]

    if selected_choice_ids.present?
      selected_choice_ids = selected_choice_ids.flatten.map(&:to_i)
    else
      flash.now[:notice] = '選択してください'
      render :wrong_display
      return
    end

    # 問題の正解のIDを取得
    correct_choice_ids = @question.choices.where(correct: true).pluck(:id)

    if correct_choice_ids.sort == (selected_choice_ids&.sort || [])
      current_user.results.update(question_id: @question.id, result: 1)
    else
      current_user.results.update(question_id: @question.id, result: 0)
    end
    redirect_to wrong_explanation_results_path(id: @question.id)
  end

  def type_other
    if params.key?(:selected_choice_id)
      # ユーザーが選択した解答のID
      selected_choice_id = params[:selected_choice_id].to_i
    else
      flash.now[:notice] = '選択してください'
      render :wrong_display
      return
    end

    # 問題の正解のIDを取得
    correct_choice_id = @question.choices.where(correct: true).pluck(:id)

    if correct_choice_id.include?(selected_choice_id)
      current_user.results.update(question_id: @question.id, result: 1)
    else
      current_user.results.update(question_id: @question.id, result: 0)
    end
    redirect_to wrong_explanation_results_path(id: @question.id)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/wrong_display.html.erb
<div class="flex items-center justify-center">
    <div class="container  dark:text-black">
        <div class="pt-10 text-question-title w-1/3 rounded-sm mx-auto">
            <h1 class="text-1xl md:text-3xl py-5 bg-question-titlebg text-center opacity-80 rounded-full"><%= t '.title' %></h1>
        </div>
        <% if @question.type != 'Nutrition' %>
        <div class="mt-10 w-3/5 opacity-80 mx-auto text-center">
            <div tabindex="0" class="collapse bg-base-200"> 
                <div class="collapse-title text-xl font-medium">
                    <i class="fa-duotone fa-block-question"></i>
                    ヒントを見る
                </div>
                <div class="collapse-content"> 
                    <%= @question.hint %>
                </div>
            </div>
        </div>
        <% end %>

        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-80 mx-auto">
            <%= form_with(url: "/results/wrong_answer", method: "post", local: true) do |form| %>
                <%= form.hidden_field :id, value: @question.id %>
                <div class="pb-5 font-light">
                    <%= @question.content %>
                </div>
                <% if @question.type == 'Compound' %>
                    <% @choices.each do |choice| %>
                        <label>
                            <%= form.check_box "selected_choice_ids[]", { multiple: true }, choice.id, nil %>
                            <%= choice.choice %>
                        </label><br>
                    <% end %>
                <% else %>
                    <% @choices.each do |choice| %>
                        <label>
                            <%= form.radio_button :selected_choice_id, choice.id %>
                            <%= choice.choice %>
                        </label><br>
                    <% end %>
                <% end %>

                <div class="mt-5 text-center">
                    <%= submit_tag '回答', class: 'btn btn-danger mx-1 bg-button-color hover:bg-hover-color button' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/results/wrong_explanation.html.erb
<div class="flex items-center justify-center">
    <div class="container">

        <%= render partial: 'shared/errata' %>

        <div class="bg-white py-5 pl-10 mt-10 w-3/5 opacity-70 mx-auto">
            <div>
                <%= @question.reason %>
            </div>
            <div class="flex justify-center mt-5">
                <%= button_to '問題選択画面へ', question_tops_index_path, class: 'btn btn-danger mx-1 bg-button-color hover:bg-hover-color button', method: :get %>
                <%= button_to '次の問題へ', wrong_display_results_path, class: 'btn btn-danger mx-1 bg-button-color hover:bg-hover-color button', method: :get %>
            </div>
        </div>
    </div>
</div>