config/routes.rb
Rails.application.routes.draw do
  get 'external_pages/show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'question_tops/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'questions#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'

    resources :questions
    post 'questions/create', to: 'questions#create', as: :create_question
  end

  resources :questions do
    collection do
      get 'nutrition_display'
      post 'nutrition_answer'
      get 'nutrition_explanation'
      get 'compound_display'
      post 'compound_answer'
      get 'compound_explanation'
    end
  end

  resources :results do
    collection do
      get 'wrong_display'
      post 'wrong_answer'
      get 'wrong_explanation'
    end
  end

  resources :external_pages, only: %i[index]
  resources :terms, only: %i[index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question

  validates  :choice, presence: true
  validates :correct, inclusion: [true, false]
end

app/models/compound.rb
class Compound < Question
end

app/models/nutrition.rb
class Nutrition < Question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :results, dependent: :destroy
  has_many :choices, dependent: :destroy

  validates  :content, presence: true
  validates  :reason, presence: true

  scope :incorrect, -> { joins(:results).where(results: { result: false }) }

  # マイステータス、円グラフのデータ抽出
  def self.nutrition_data(user)
    nutrition_count = where(type: 'Nutrition').count
    nutrition_true_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: true }).count
    nutrition_false_count = joins(:results).where(type: 'nutrition', results: { user_id: user.id, result: false }).count
    not_answer_count = nutrition_count - (nutrition_true_count + nutrition_false_count)

    { '正解' => nutrition_true_count, '不正解' => nutrition_false_count, '未回答' => not_answer_count }
  end

  def self.compound_data(user)
    compound_count = where(type: 'Compound').count
    compound_true_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: true }).count
    compound_false_count = joins(:results).where(type: 'compound', results: { user_id: user.id, result: false }).count
    not_answer_count = compound_count - (compound_true_count + compound_false_count)

    { '正解' => compound_true_count, '不正解' => compound_false_count, '未回答' => not_answer_count }
  end

  # 残りの問題数の取得
  def self.nutrition_rest_count(user)
    rest_count = Result.nutrition_count(user)
    questions_count = Question.where(type: 'nutrition').count
    questions_count - rest_count
  end

  def self.compound_rest_count(user)
    rest_count = Result.compound_count(user)
    questions_count = Question.where(type: 'compound').count
    questions_count - rest_count
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  has_many :users

  validates :rank_name, presence: true
  validates :response, presence: true

  def self.calculate_rank(user)
    new_rank = nil
    # ユーザーの正解の回答数を取得
    result_count = Result.result_count(user)

    # 　ランク一覧をデータベースから取得
    ranks = Rank.order(response: :asc)
    ranks.each do |rank|
      if rank.response >= result_count
        new_rank = rank
        break # ユーザーのランクが見つかったらループ終了
      end
    end
    new_rank
  end
end

app/models/result.rb
class Result < ApplicationRecord
  enum result: { failure: 0, success: 1 }

  belongs_to :user
  belongs_to :question

  validates  :result, presence: true
  validates :question_id, uniqueness: { scope: :user_id }

  # 与えられたユーザーのresultカラムがtrueのレコード数を取得
  def self.result_count(user)
    where(user_id: user.id, result: true).count
  end

  # 回答した問題数の取得
  def self.nutrition_count(user)
    Result.joins(:question).where(questions: { type: 'nutrition' }).where(user_id: user.id).count
  end

  def self.compound_count(user)
    Result.joins(:question).where(questions: { type: 'compound' }).where(user_id: user.id).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum role: { general: 0, admin: 1 }

  has_many :results, dependent: :destroy
  belongs_to :rank, optional: true

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { minimum: 2 }

  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :check_admin, only: %i[new create]

  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to admin_root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to admin_login_path, success: t('.success')
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def show
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  layout 'top'
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to profile_path, notice: t('.success')
    else
      flash.now[:alert] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: t('.success')
  end
end

app/helpers/admin/user_sessions_helper.rb
module Admin::UserSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
        site: 'FoodFit',
        title: '栄養に関する学習クイズサイト',
        reverse: true,
        charset: 'utf-8',
        description: 'FoodFitで日常で役立つ栄養学習が手軽に行えます',
        keywords: '栄養,クイズ,食事',
        canonical: request.original_url,
        separator: '|',
        og: {
            site_name: :site,
            title: :title,
            description: :description,
            type: 'website',
            url: request.original_url,
            image: image_url('ogp.jpg'),
            local: 'ja_JP'
        },

        twitter: {
            card: 'summary_large_image',
            image: image_url('ogp.jpg')
        }
    }
  end
end

app/helpers/conpunds_helper.rb
module ConpundsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/user_sessions/new.html.erb
<div class="container text-center mx-auto">
    <h1 class="text-2xl text-black-200 pt-10"><%= t '.title' %></h1>
    <div class="form-gorup py-5 flex justify-center">
        <%= form_with url: admin_login_path, local: true do |f| %>
            <div class="text-black-200 text-2xl">
                <div class = "form-group py-5">
                    <%= f.label :email, User.human_attribute_name(:email), class: "text-black-200 text-3xl" %>
                    <%= f.email_field :email, class: "form-control text-2xl rounded-full"  %>
                </div>
                <div class="form-group py-5">
                    <%= f.label :password, User.human_attribute_name(:password), class: "text-black-200 text-3xl" %>
                    <%= f.password_field :password, class: "form-control text-2xl rounded-full" %>
                </div>
                <div class="form-group py-5 text-center">
                    <%= f.submit (t 'defaults.login'), class: 'btn btn-primary rounded-full text-2xl py-5 px-10' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/user_sessions/new.html.erb
<div class="flex items-center justify-center">
    <div class="container">
        <div class="pt-10 text-font-color w-1/3 rounded-sm mx-auto">
            <h1 class="text-2xl md:text-4xl py-5 text-center"><%= t '.title' %></h1>
        </div>

        <div class="flex justify-center form-gorup py-5">
        
            <%= form_with url: login_path, local: true do |f| %>
                <div class="text-text-color md:text-2xl">
                    <div class = "form-group py-5">
                        <%= f.label :email, User.human_attribute_name(:email), class: "text-font-color text-1xl md:text-3xl" %>
                        <%= f.email_field :email, class: "form-control mb-3 py-3 px-10 mt-3 rounded-full  text-base md:text-2xl dark:bg-white" %>
                    </div>
                    <div class="form-group py-5">
                        <%= f.label :password, User.human_attribute_name(:password), class: "text-font-color text-1xl md:text-3xl" %>
                        <%= f.password_field :password, class: "form-control mb-3 mb-3 py-3 px-10 mt-3 rounded-full  text-base md:text-2xl dark:bg-white" %>
                    </div>
                    <div class="form-group py-5 text-center">
                        <%= f.submit (t 'defaults.login'), class: 'btn btn-primary bg-button-color hover:bg-hover-color text-button-font border-none rounded-full py-5 px-10 button' %>
                    </div>
                </div>
            <% end %>
        </div>

        <div class='text-center dark:text-black'>
            <div class="pb-5">
                <%= link_to t('.password_forgot'), new_password_reset_path, class: "text-base md:text-2xl hover:underline" %>
            </div>
            <div>
                <%= link_to t('.to_register_page'), new_user_path, class: "text-base md:text-2xl hover:underline" %>
            </div>
        </div>
    </div>
</div>